[package]
name = "myredis"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1"
mini-redis = "0.4.1"
tokio = { version = "1.38.0", features = ["full"] }

[lib]
path = "src/lib.rs"

[[bin]]
name = "server"
path = "src/bin/server.rs"

[[bin]]
name = "client"
path = "src/bin/client.rs"
